// <auto-generated />
using System;
using DbRelationshipsForDevelopersProjectsPOC.DbEntites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbRelationshipsForDevelopersProjectsPOC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbRelationshipsForDevelopersProjectsPOC.DbEntites.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("DbRelationshipsForDevelopersProjectsPOC.DbEntites.DeveloperProjects", b =>
                {
                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeveloperId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("DeveloperProjects");
                });

            modelBuilder.Entity("DbRelationshipsForDevelopersProjectsPOC.DbEntites.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DbRelationshipsForDevelopersProjectsPOC.DbEntites.DeveloperProjects", b =>
                {
                    b.HasOne("DbRelationshipsForDevelopersProjectsPOC.DbEntites.Developer", "Developer")
                        .WithMany("Project")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbRelationshipsForDevelopersProjectsPOC.DbEntites.Project", "Project")
                        .WithMany("Developer")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DbRelationshipsForDevelopersProjectsPOC.DbEntites.Developer", b =>
                {
                    b.Navigation("Project");
                });

            modelBuilder.Entity("DbRelationshipsForDevelopersProjectsPOC.DbEntites.Project", b =>
                {
                    b.Navigation("Developer");
                });
#pragma warning restore 612, 618
        }
    }
}
